bulletin/urls.py
from django.urls import path

from . import views

# アプリケーションの名前空間
# https://docs.djangoproject.com/ja/2.0/intro/tutorial03/
app_name = 'bulletin'

urlpatterns = [
    # ex: /
    path('', views.index, name='index'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),
    path('post/<int:pk>/comment/new', views.comment_new, name='comment_new'),
    path('post/<int:pk>/comment/<int:commentid>/edit', views.comment_edit, name='comment_edit'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('mypage/', views.mypage, name='mypage'),
    path('mypage/article_list', views.article_list, name='article_list'),
    # # ex: /post/create/
    # path('post/create/', views.create, name='create'),
    #
    # # ex: /post/1/
    # path('post/<int:pk>/', views.detail, name='detail'),
    #
    # # ex: /post/1/update/
    # path('post/<int:pk>/update/', views.update, name='update'),
    #
    # # ex: /post/1/delete
    # path('post/<int:pk>/delete/', views.delete, name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.conf.urls.static import static
# from mysite import settings

# from mysite import settings
# from . import views

app_name = 'mysite'

urlpatterns = [
    path('', include('bulletin.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# 以下を定義
# 画像アップロードのテスト
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bulletin/models.py
from django.db import models
from django.utils import timezone
from accounts.models import User


class Post(models.Model):
    # author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE, null=False)
    title = models.CharField(max_length=200)
    text = models.TextField()
    draft_flg = models.CharField(max_length=1, default='0')
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Comment(models.Model):
    # author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE, null=False)
    postid = models.ForeignKey('bulletin.Post', on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

class Access(models.Model):
    postid = models.ForeignKey('bulletin.Post', on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

bulletin/forms.py
from django import forms

from .models import Post, Comment

class PostForm(forms.ModelForm):
    CHOICE = {
        ('0','公開'),
        ('1','下書き'),
    }
    draft_flg = forms.ChoiceField(label='状態', widget=forms.RadioSelect, choices= CHOICE, initial=0)

    class Meta:
        model = Post
        fields = ('title', 'text', 'draft_flg',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

bulletin/views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import PostForm, CommentForm
import datetime #<- 追記
from django.utils import timezone #<- 追記
from .models import Post, Comment
from .services.LoggerService import LoggerService as ls
from .services.AccessService import AccessService
from .services.PaginateService import PaginateService as ps
from accounts.models import User
from django.http import Http404
from django.conf import settings

# Create your views here.
def index(request):
    posts = Post.objects.order_by('-published_date').all().exclude(draft_flg='1')
    page_obj = ps.paginate_query(request, posts, settings.PAGE_PER_ITEM)
    return render(request, 'bulletin/index.html', {'page_obj': page_obj})

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.publish()
            accessService = AccessService()
            accessService.countup(post)
            return redirect('/post/' + str(post.pk), pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'bulletin/post_edit.html', {'form': form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    # 記事の作者がログインユーザと違う場合はエラー
    if post.author != request.user:
        raise Http404

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.publish()
            return redirect('/post/' + str(pk), pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'bulletin/post_edit.html', {'form': form})

def post_detail(request, pk):
    # 記事の検索をしつつ、無い場合は404エラーを返す
    post = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(postid=post)
    accessService = AccessService()
    accessService.countup(post)
    return render(request, 'bulletin/post_detail.html', {'post': post,'comments' : comments})

@login_required
def comment_new(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            ls.file("userid is " + str(comment.author.id))
            comment.postid = post
            comment.published_date = timezone.now()
            comment.publish()
            return redirect('/post/' + str(pk), pk=pk)
    else:
        form = CommentForm()
    return render(request, 'bulletin/comment_edit.html', {'form': form})

@login_required
def comment_edit(request, pk, commentid):
    comment = get_object_or_404(Comment, pk=commentid)
    post = get_object_or_404(Post, pk=pk)
    # コメントの作者が違う場合はエラー
    if comment.author != request.user:
        raise Http404

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.postid = post
            comment.published_date = timezone.now()
            comment.publish()
            return redirect('/post/' + str(pk), pk=pk)
    else:
        form = CommentForm(instance=comment)
    return render(request, 'bulletin/comment_edit.html', {'form': form })

@login_required
def mypage(request):
    user = get_object_or_404(User, pk=request.user.id)
    return render(request, 'bulletin/mypage.html')

@login_required
def article_list(request):
    user = get_object_or_404(User, pk=request.user.id)
    posts = Post.objects.filter(author=user)
    return render(request, 'bulletin/article_list.html', {'posts': posts })

@login_required
def post_delete(request, pk):
    user = get_object_or_404(User, pk=request.user.id)
    post = get_object_or_404(Post, pk=pk)
    # 記事の作者がログインユーザと違う場合はエラー
    if post.author != request.user:
        raise Http404
    post.delete()
    return redirect('/')

bulletin/templates/bulletin/article_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% block extrahead %}
      <link href="{% static 'css/index.css' %}" rel="stylesheet">
    {% endblock %}
    <h1>記事一覧</h1>
    {% for post in posts %}
      <div class="cardWrapper">
      <div class="card m-2">
          <div class="card-title bg-dark">
            <div class="row m-2">
              <div class="col-6 titleContainer">
                <a href="/post/{{ post.pk }}">
                  {{ post.title }}
                </a>
                {% if post.draft_flg == "1" %}
                  &nbsp;&nbsp;<div class="btn btn-primary">下書き</div>
                {% endif %}
              </div>
              <div class="col-3 titleContainer"><span>閲覧数</span></div>
              <div class="col-3 titleContainer"><span>返信数</span></div>
            </div>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-6 textOverFlow text">{{ post.text }}</div>
              <div class="col-3">{{ post.access_set.all.0.count }}</div>
              <div class="col-3">{{ post.comment_set.all|length }}</div>
            </div>
          </div>
          <div class="card-footer">
            <span>{{ post.published_date }}</span>
            <span>&nbsp;&nbsp;by&nbsp;{{ post.author }}</span>
            <span>&nbsp;&nbsp;<a class="btn border btn-default" href="{% url 'bulletin:post_edit' pk=post.pk %}">編集する</a></span>
            <span>&nbsp;&nbsp;<a class="btn border btn-default" href="{% url 'bulletin:post_delete' pk=post.pk %}">削除する</a></span>
          </div>
        </div>
      </div>
    {% endfor %}
{% endblock %}

bulletin/templates/bulletin/comment_edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <h1>コメントを書く</h1>
    <form method="POST" class="post-form">{% csrf_token %}
      <div class="form-group">
        <label>コメント:</label>
        {{ form.text|add_class:"form-control" }}
      </div>
        <button type="submit" class="save border btn btn-default">投稿する</button>
    </form>
{% endblock %}

bulletin/templates/bulletin/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% block extrahead %}
      <link href="{% static 'css/index.css' %}" rel="stylesheet">
    {% endblock %}
    <h1>記事一覧</h1>
    {% for post in page_obj %}
      <div class="cardWrapper">
      <div class="card m-2">
          <div class="card-title bg-dark">
            <div class="row m-2">
              <div class="col-6 titleContainer">
                <a href="/post/{{ post.pk }}">
                  {{ post.title }}
                </a>
              </div>
              <div class="col-3 titleContainer"><span>閲覧数</span></div>
              <div class="col-3 titleContainer"><span>返信数</span></div>
            </div>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-6 textOverFlow text">{{ post.text }}</div>
              <div class="col-3">{{ post.access_set.all.0.count }}</div>
              <div class="col-3">{{ post.comment_set.all|length }}</div>
            </div>
          </div>
          <div class="card-footer">
            <span>{{ post.published_date }}</span>
            <span>&nbsp;&nbsp;by&nbsp;{{ post.author }}</span>
          </div>
        </div>
      </div>
    {% endfor %}

    <div>
      <nav aria-label="Page navigation example">
          <ul class="pagination">
              {% if page_obj.has_previous %}
                  <li><a class="page-link d-inline-block" href="?page={{ page_obj.previous_page_number }}">前</a></li>
              {% else %}
                  <li class="disabled"><div class="page-link text-secondary d-inline-block disabled" href="#">前</div></li>
              {% endif %}

              {% for link_page in page_obj.paginator.page_range %}
                  {% if link_page %}
                      {% if link_page == page_obj.number %}
                          <li class="disabled"><div class="page-link text-secondary d-inline-block disabled" href="#">{{ link_page }}</div></li>
                      {% else %}
                          <li><a class="page-link d-inline-block" href="?page={{ link_page }}">{{ link_page }}</a></li>
                      {% endif %}
                  {% else %}
                      <li class="disabled"><a class="page-link text-secondary d-inline-block text-muted" href="#">・・・</a></li>
                  {% endif %}
              {% endfor %}

              {% if page_obj.has_next %}
                  <li><a class="page-link d-inline-block" href="?page={{ page_obj.next_page_number }}">次</a></li>
              {% else %}
                  <li class="disabled"><div class="page-link text-secondary d-inline-block disabled" href="#">次</div></li>
              {% endif %}
          </ul>
      </nav>
    </div>
{% endblock %}

bulletin/templates/bulletin/mypage.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <h1>マイページ</h1>
    <a href="/mypage/article_list">記事一覧</a>
    <a href="/accounts/profile_edit">プロフィール編集</a>
{% endblock %}

bulletin/templates/bulletin/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  {% block extrahead %}
    <link href="{% static 'css/post_detail.css' %}" rel="stylesheet">
  {% endblock %}
  <div class="post">
      <a class="btn border btn-default" href="{% url 'bulletin:comment_new' pk=post.pk %}"><span class="">コメントをする</span></a>
      <div class="cardWrapper">
      <div class="card m-2">
          <div class="card-title bg-dark">
            <div class="row m-2 titleContainer">
                <div style="color:white">
                  {{ post.title }}
                </div>
            </div>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-4 profileImgContainer">
                <img class="profile" src="{% static 'img/profile.png' %}">
                <div>{{ post.author }}</div>
              </div>
              <div class="col-8 text">
                {{ post.text | urlize | linebreaksbr }}
              </div>
            </div>
          </div>
          <div class="card-footer">
            <span>{{ post.published_date }}</span>
          </div>
        </div>
      </div>
  </div>
  {% for comment in comments %}
  <div class="post">
      <div class="cardWrapper">
      <div class="card m-2">
          <div class="card-body">
            <div class="row">
              <div class="col-4 profileImgContainer">
                <img class="profile" src="{% static 'img/profile.png' %}">
                <div>{{ comment.author }}</div>
              </div>
              <div class="col-8 text">
                {{ comment.text | urlize | linebreaksbr }}
              </div>
            </div>
          </div>
          <div class="card-footer">
            <span>{{ comment.published_date }}</span>
            {% if comment.author == user %}
              <span>&nbsp;&nbsp;<a class="btn border btn-default" href="{% url 'bulletin:comment_edit' pk=post.pk commentid=comment.id %}">編集する</a></span>
            {% endif %}
          </div>
        </div>
      </div>
  </div>
  {% endfor %}
{% endblock %}

bulletin/templates/bulletin/post_edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <h1>記事を投稿する</h1>
    <form method="POST" class="post-form">{% csrf_token %}
      <div class="form-group">
        <label>タイトル:</label>
        {{ form.title|add_class:"form-control" }}
      </div>
      <div class="form-group">
        <label>内容:</label>
        {{ form.text|add_class:"form-control" }}
      </div>
      <div class="form-group">
        <label>公開か下書きか:</label>
        {{ form.draft_flg }}
      </div>
      <button type="submit" class="save border btn btn-default">Save</button>
    </form>
{% endblock %}